v5 devel branch (#307)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,33 +1,38 @@
-#!/usr/bin/env bash
-# SPDX-FileCopyrightText: 2024 geisserml <geisserml@gmail.com>
+#!/usr/bin/env -S bash -eu
+# SPDX-FileCopyrightText: 2025 geisserml <geisserml@gmail.com>
 # SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause
 
-# FIXME can we support running multiple commands at once ?
-# FIXME auto-completion
+# TODO: auto-completion?, running multiple commands at once?
 
 args="${@:2}"
 
 function check() {
-    autoflake src/ setupsrc/ tests/ tests_old/ setup.py docs/source/conf.py --recursive --remove-all-unused-imports --ignore-pass-statements --ignore-init-module-imports
-    codespell --skip="./docs/build,./tests/resources,./tests/output,./tests_old/output,./data,./sourcebuild,./dist,./.git,__pycache__,.mypy_cache,.hypothesis" -L "tabe,splitted,fith,flate"
+    autoflake src/ setupsrc/ tests/ setup.py docs/source/conf.py --recursive --remove-all-unused-imports --ignore-pass-statements --ignore-init-module-imports
+    codespell --skip="./docs/build,./tests/resources,./tests/output,./data,./sourcebuild,./dist,./LICENSES/*,./RELEASE.md,./.git,__pycache__,.mypy_cache,.hypothesis" -L "FitH,flate"
     reuse lint
 }
 
 function clean() {
-    rm -rf pypdfium2*.egg-info/ src/pypdfium2*.egg-info/ build/ dist/ data/* tests/output/* tests_old/output/* conda/bundle/out/ conda/helpers/out/ conda/raw/out/
+    rm -rf pypdfium2*.egg-info/ src/pypdfium2*.egg-info/ build/ dist/ data/* tests/output/* conda/bundle/out/ conda/helpers/out/ conda/raw/out/
 }
 
 function packaging_pypi() {
+    # Note, in the future, we might want to add some `|| true` to avoid failing the release workflow just because of an autoflake/codespell/reuse complaint.
     clean
     check
 
-    # calling update_pdfium is not strictly necessary, but may improve performance because downloads are done in parallel, rather than linear with each package
-    python3 setupsrc/pypdfium2_setup/update_pdfium.py
-    python3 setupsrc/pypdfium2_setup/craft_packages.py pypi
+    # calling update.py is not strictly necessary, but may improve performance because downloads are done in parallel, rather than linear with each package
+    python3 setupsrc/pypdfium2_setup/update.py
+    python3 setupsrc/pypdfium2_setup/craft.py
 
     twine check dist/*
     # ignore W002: erroneous detection of __init__.py files as duplicates
     check-wheel-contents dist/*.whl --ignore W002 --toplevel "pypdfium2,pypdfium2_raw"
+}
+
+function coverage_impl() {
+    python3 -m coverage run --omit "$OMISSIONS" -m pytest tests/ $args
+    python3 -m coverage report
 }
 
 set -x
@@ -35,11 +40,15 @@ set -x
 case $1 in
 
 test)
-    python3 -m pytest tests/ tests_old/ $args;;
+    python3 -m pytest tests/ $args;;
 
 coverage)
-    python3 -m coverage run --omit "tests/*,tests_old/*,src/pypdfium2_raw/bindings.py,setupsrc/*" -m pytest tests/ tests_old/ $args
-    python3 -m coverage report;;
+    OMISSIONS="src/pypdfium2_raw/bindings.py,tests/*,setupsrc/*"
+    coverage_impl;;
+
+coverage-core)
+    OMISSIONS="src/pypdfium2/__main__.py,src/pypdfium2/_cli/*,src/pypdfium2_raw/bindings.py,tests/*,setupsrc/*"
+    coverage_impl;;
 
 docs-build)
     python3 -m sphinx -b html docs/source docs/build/html $args;;
@@ -57,13 +66,16 @@ packaging_pypi)
     packaging_pypi;;
 
 update)
-    python3 setupsrc/pypdfium2_setup/update_pdfium.py $args;;
+    python3 setupsrc/pypdfium2_setup/update.py $args;;
 
 craft)
-    python3 setupsrc/pypdfium2_setup/craft_packages.py $args;;
+    python3 setupsrc/pypdfium2_setup/craft.py $args;;
+
+craft-conda)
+    python3 conda/craft_conda_pkgs.py $args;;
 
 build)
-    python3 setupsrc/pypdfium2_setup/build_pdfium.py $args;;
+    python3 setupsrc/pypdfium2_setup/sourcebuild.py $args;;
 
 emplace)
     python3 setupsrc/pypdfium2_setup/emplace.py $args;;
